name: Deploy Next.js to Cloudflare Pages

on:
  push:
    branches:
      - main  # अगर तुम्हारी मुख्य ब्रांच का नाम master है, तो गिटहब इसे अपने आप संभाल लेगा

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Next-on-Pages
        run: npx @cloudflare/next-on-pages
        env:
          NEXT_PUBLIC_TMDB_API_KEY: '174d0214bf933dd59b3d5ec68a0c967f' # तुम्हारी TMDB API Key

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'u-tv' # तुम्हारी साइट u-tv.pages.dev का नाम
          directory: '.cloudflare'
